package ua.foxminded.carrestservice.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

/**
 * Abstract base class for entities in the car rest service system.
 * Provides a common {@code id} field with auto-incremented primary key for all extending entities.
 * Annotated with {@code @MappedSuperclass} to share properties with subclasses without being
 * persisted as a separate table. Uses Lombok annotations for boilerplate code reduction.
 *
 * @author Serhii Bohdan
 * @see jakarta.persistence.MappedSuperclass
 * @see jakarta.persistence.Id
 * @see jakarta.persistence.GeneratedValue
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@SuperBuilder
@MappedSuperclass
public abstract class AbstractEntity {

    /**
     * Unique identifier for the entity.
     * Auto-incremented primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

}
