server:
  port: 8082

spring:
  application:
    name: car-rest-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_service
    username: postgres
    password: pass

  jpa:
    open-in-view: false
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-daubxi5a4rxojbok.us.auth0.com/
          audiences: https://car-service-api.dev
