# OpenApi documentation
open-api.info.title=Car REST Service
open-api.info.description=A RESTful API for managing car-related data
open-api.info.version=1.0.0
open-api.info.contact.email=serhii.bohdan99@gmail.com
open-api.servers.url=http://localhost:8082/

# OAuth 2.0 security
security.oauth2.token.access.url=https://dev-daubxi5a4rxojbok.us.auth0.com/oauth/token
security.oauth2.client.id=mbnB4FzyDR4WgNbfiZuWKmaQPl01C8Cx
security.oauth2.client.secret=l4hmA1olqYxLp8VCNpGEaBiyT_uX2Wavh9abO5psXE1Qyz6g0pRi0BCYWQYFjoIm
security.oauth2.audience=https://car-service-api.dev
security.oauth2.grant.type=client_credentials
